config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :devices
  resources :offers do
    resources :offer_targets, path: 'targets', only: [:index]
  end
  
  resources :offer_targets


  root to: 'players#index'
end


# web: bin/rails server -p 3000

app/models/device.rb
class Device < ApplicationRecord
  include Osable
  include Localeable

  belongs_to :player

  validates_presence_of :device_model
  validates_presence_of :os
  validates_presence_of :os_version
  validates_presence_of :locale

  scope :os_versions_gte, ->(version) { where('os_version >= ?', version) }
  scope :os_versions_lte, ->(version) { where('os_version <= ?', version) }

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:edit, :update, :show, :destroy]

  def index
    @devices = Device.joins(:player).order(os_version: :asc)

    if params[:min_os].present?
      @devices = @devices.os_versions_gte(params[:min_os])
    end

    if params[:max_os].present?
      @devices = @devices.os_versions_lte(params[:max_os])
    end
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)
    if @device.save
      redirect_to devices_path, notice: 'Device Created.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @device.update(device_params)
      redirect_to devices_path, notice: 'Device Updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @device.destroy
    redirect_to devices_path, notice: 'Device Destroyed.'
  end


  private

    def set_device
      @device = Device.find(params[:id])
    end

    def device_params
      params.require(:device).permit(
        :player_id,
        :device_model,
        :os,
        :os_version,
        :locale,
      )
    end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.slim
=form_for @device, class: 'space-y-8.divide-y.divide-gray-200' do |f|
  - if @device.errors.any?
    #error_explanation
      h2 = "#{pluralize(@device.errors.count, 'error')} prohibited this device from being saved:"
      ul
        - @device.errors.full_messages.each do |message|
          li = message

  .space-y-8.divide-y.divide-gray-200
    .pt-8
      div
        h3.text-lg.leading-6.font-medium.text-gray-900
          =local_assigns[:title]
      .mt-6.grid.grid-cols-1.gap-y-6.gap-x-4
        .col-span-3
          =select_collection(f, Player, :player_id, Player.without_device.order(first_name: :asc), :id, :full_name, 'Player')

        .col-span-3
          =f.label :device_model, 'Model', class: "block text-sm font-medium text-gray-700"
          =f.text_field :device_model, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'
        
        .col-span-3
          =select_enum f, :os
        
        .col-span-3
          =f.label :os_version, class: "block text-sm font-medium text-gray-700"
          =f.text_field :os_version, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =select_enum f, :locale
  .pt-5
    .flex.justify-end
      =link_to 'Cancel', devices_path, class: " bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
  
      =f.submit 'Save', class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/devices/edit.html.slim
=render 'form', title: 'Edit Device'

app/views/devices/index.html.slim
h1.mb-5
  =pluralize(@devices.count, 'Device')

=form_with url: devices_path, method: :get do
  .mt-6.grid.grid-cols-12.gap-y-6.gap-x-4
    .col-span-2
      =label_tag :min_os, 'Min OS Version', class: "block text-sm font-medium text-gray-700"
      =text_field_tag :min_os, params[:min_os], class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block sm:text-sm border-gray-300 rounded-md'

    .col-span-2
      =label_tag :max_os, 'Max OS Version', class: "block text-sm font-medium text-gray-700"
      =text_field_tag :max_os, params[:max_os], class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block sm:text-sm border-gray-300 rounded-md'

    .col-span-2.flex
      =submit_tag 'Search', class: "py-2 px-4 self-end border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"


.my-5.text-right
  =link_to 'Add Device', new_device_path, class: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

.flex.flex-col
  .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
    .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
      .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
        table.min-w-full.divide-y.divide-gray-200
          thead.bg-gray-50
            tr
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Player
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Model
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | OS
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | OS Version
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Locale
              th.relative.px-6.py-3[scope="col"]
                span.sr-only
                  | Edit
              th.relative.px-6.py-3[scope="col"]
                span.sr-only
                  | Destroy
          tbody
            -@devices.each do |device|
              tr.hover:bg-slate-50
                td.px-6.py-4.whitespace-nowrap.text-sm.font-medium.text-gray-900
                  =device.player.full_name
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =device.device_model
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =device.os
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =device.os_version
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =device.locale
                td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
                  =link_to 'edit', edit_device_path(device), class: "text-indigo-600 hover:text-indigo-900"
                td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
                  =button_to 'destroy', device, class: "text-indigo-600 hover:text-indigo-900", method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }

app/views/devices/new.html.slim
=render 'form', title: 'Create New Device'