config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :devices
  resources :offers do
    resources :offer_targets, path: 'targets', only: [:index]
  end
  
  resources :offer_targets


  root to: 'players#index'
end


# web: bin/rails server -p 3000

app/models/offer_target.rb
class OfferTarget < ApplicationRecord
  include Genderable
  include Osable
  include Localeable

  belongs_to :offer

  validates_presence_of :min_age
  validates_presence_of :max_age
  validates_presence_of :gender
  validates_presence_of :os
  validates_presence_of :min_os_version
  validates_presence_of :locale

  validates_numericality_of :min_age, greater_than: 10
  validates_numericality_of :max_age

  validate :min_age_lt_max_age

  scope :age_gte, ->(age) { where('min_age >= ?', age) }
  scope :age_lte, ->(age) { where('max_age <= ?', age) }
  scope :ages_between, ->(min_age, max_age) { age_gte(min_age).age_lte(max_age) }
  scope :os_versions_gte, ->(min_ver) { where('min_os_version >= ?', min_ver) }



  private

    def min_age_lt_max_age
      if min_age.to_i >= max_age.to_i
        errors.add :base, :invalid, message: "Minimum age needs to be larger than the maximum age"
      end
    end

end

app/controllers/offer_targets_controller.rb
class OfferTargetsController < ApplicationController
  before_action :set_offer_target, only: [:edit, :update, :show, :destroy]

  def index
    @offer_targets = OfferTarget.order(offer_id: :asc)
  
    if params[:offer_id].present?
      offer = Offer.find(params[:offer_id])
      @offer_targets = @offer_targets.where(offer: offer)
    end
  end

  def new
    @offer_target = OfferTarget.new
  end

  def create
    @offer_target = OfferTarget.new(offer_target_params)
    if @offer_target.save
      redirect_to offer_targets_path, notice: 'Offer Target Created.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @offer_target.update(offer_target_params)
      redirect_to offer_targets_path, notice: 'Offer Target Updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @offer_target.destroy
    redirect_to offer_targets_path, notice: 'Offer Target Destroyed.'
  end


  private

    def set_offer_target
      @offer_target = OfferTarget.find(params[:id])
    end

    def offer_target_params
      params.require(:offer_target).permit(
        :offer_id,
        :min_age,
        :max_age,
        :gender,
        :os,
        :min_os_version,
        :locale
      )
    end

end

app/helpers/offer_targets_helper.rb
module OfferTargetsHelper
end

app/views/offer_targets/_form.html.slim
=form_for @offer_target, class: 'space-y-8.divide-y.divide-gray-200' do |f|
  - if @offer_target.errors.any?
    #error_explanation
      h2 = "#{pluralize(@offer_target.errors.count, 'error')} prohibited this offer_target from being saved:"
      ul
        - @offer_target.errors.full_messages.each do |message|
          li = message

  .space-y-8.divide-y.divide-gray-200
    .pt-8
      div
        h3.text-lg.leading-6.font-medium.text-gray-900
          =local_assigns[:title]
      .mt-6.grid.grid-cols-1.gap-y-6.gap-x-4
        .col-span-3
          =select_collection(f, Offer, :offer_id, Offer.all, :id, :title, 'Offer')

        .col-span-3
          =f.label :min_age, class: "block text-sm font-medium text-gray-700"
          =f.text_field :min_age, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =f.label :max_age, class: "block text-sm font-medium text-gray-700"
          =f.text_field :max_age, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =select_enum f, :gender

        .col-span-3
          =select_enum f, :os
        
        .col-span-3
          =f.label :min_os_version, class: "block text-sm font-medium text-gray-700"
          =f.text_field :min_os_version, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =select_enum f, :locale
  .pt-5
    .flex.justify-end
      =link_to 'Cancel', devices_path, class: " bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
  
      =f.submit 'Save', class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/offer_targets/edit.html.slim
=render 'form', title: 'Edit Offer Target'

app/views/offer_targets/index.html.slim
h1.mb-5
  =pluralize(@offer_targets.count, 'Offer Target')

.my-5.text-right
  =link_to 'Add Offer Target', new_offer_target_path, class: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

.flex.flex-col
  .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
    .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
      .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
        table.min-w-full.divide-y.divide-gray-200
          thead.bg-gray-50
            tr
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Offer
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Min Age
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Max Age
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Gender
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | OS
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Min OS Version
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Locale
              th.relative.px-6.py-3[scope="col"]
                span.sr-only
                  | Edit
              th.relative.px-6.py-3[scope="col"]
                span.sr-only
                  | Destroy
          tbody
            -@offer_targets.each do |offer_target|
              tr.hover:bg-slate-50
                td.px-6.py-4.whitespace-nowrap.text-sm.font-medium.text-gray-900
                  =offer_target.offer
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer_target.min_age
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer_target.max_age
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer_target.gender
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer_target.os
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer_target.min_os_version
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer_target.locale
                  
                td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
                  =link_to 'edit', edit_offer_target_path(offer_target), class: "text-indigo-600 hover:text-indigo-900"                  
                td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
                  =button_to 'destroy', offer_target, class: "text-indigo-600 hover:text-indigo-900", method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }

app/views/offer_targets/new.html.slim
=render 'form', title: 'Create New Offer Target'