config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :devices
  resources :offers do
    resources :offer_targets, path: 'targets', only: [:index]
  end
  
  resources :offer_targets


  root to: 'players#index'
end


# web: bin/rails server -p 3000

app/models/offer.rb
class Offer < ApplicationRecord

  has_many :offer_targets, dependent: :destroy

  validates_presence_of :title
  validates_presence_of :header
  validates_presence_of :description
  validates_numericality_of :points, greater_than: 1
  validates_numericality_of :payout, greater_than: 1.0

  def to_s
    title
  end


  def self.total_payout_for_players_between_ages(min_age, max_age)
    # SELECT SUM(Q2.payout)
    # FROM (
    #         SELECT
    #           offers.id,
    #           P1.id,
    #           offers.payout
    #         FROM (SELECT id, DATE_PART('year', AGE('2022-02-28', birthdate)) AS years_old from players) P1
    #                   INNER JOIN
    #               offer_targets ON P1.years_old BETWEEN offer_targets.min_age AND offer_targets.max_age
    #                   INNER JOIN
    #               offers ON offers.id = offer_targets.offer_id
    #          GROUP by offers.id, P1.id
    #      ) Q2

    Offer
      .joins(:offer_targets)
      .joins("INNER JOIN (#{Player.ages.to_sql}) ages ON ages.years_old BETWEEN offer_targets.min_age AND offer_targets.max_age")
      .group("offers.id, ages.id")
      .where('offer_targets.min_age >= ? AND offer_targets.max_age <= ?', min_age, max_age)
      .sum(&:payout).to_f
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:edit, :update, :show, :destroy]

  def index
    @offers = Offer.order(title: :asc)

    if params[:min_age].present? && params[:max_age].present?
      @player_payout = Offer.total_payout_for_players_between_ages(params[:min_age], params[:max_age])
    end
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    if @offer.save
      redirect_to offers_path, notice: 'Offer Created.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @offer.update(offer_params)
      redirect_to offers_path, notice: 'Offer Updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @offer.destroy
    redirect_to offers_path, notice: 'Offer Destroyed.'
  end


  private

    def set_offer
      @offer = Offer.find(params[:id])
    end

    def offer_params
      params.require(:offer).permit(
        :player_id,
        :title,
        :header,
        :description,
        :points,
        :payout
      )
    end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.slim
=form_for @offer, class: 'space-y-8.divide-y.divide-gray-200' do |f|
  - if @offer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@offer.errors.count, 'error')} prohibited this offer from being saved:"
      ul
        - @offer.errors.full_messages.each do |message|
          li = message

  .space-y-8.divide-y.divide-gray-200
    .pt-8
      div
        h3.text-lg.leading-6.font-medium.text-gray-900
          =local_assigns[:title]
      .mt-6.grid.grid-cols-1.gap-y-6.gap-x-4
        .col-span-3
          =f.label :title, class: "block text-sm font-medium text-gray-700"
          =f.text_field :title, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =f.label :header, class: "block text-sm font-medium text-gray-700"
          =f.text_field :header, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =f.label :description, class: "block text-sm font-medium text-gray-700"
          =f.text_area :description, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =f.label :points, class: "block text-sm font-medium text-gray-700"
          =f.text_field :points, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

        .col-span-3
          =f.label :payout, class: "block text-sm font-medium text-gray-700"
          =f.text_field :payout, value: number_to_currency(@offer.payout, unit: ""), class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md'

  .pt-5
    .flex.justify-end
      =link_to 'Cancel', offers_path, class: " bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
  
      =f.submit 'Save', class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/offers/edit.html.slim
=render 'form', title: 'Edit Offer'

app/views/offers/index.html.slim
h1.mb-5
  =pluralize(@offers.count, 'Offer')

=form_with url: offers_path, method: :get do
  .mt-6.grid.grid-cols-12.gap-y-6.gap-x-4
    .col-span-2
      =label_tag :min_age, 'Minimum Age', class: "block text-sm font-medium text-gray-700"
      =text_field_tag :min_age, params[:min_age], class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block sm:text-sm border-gray-300 rounded-md'

    .col-span-2
      =label_tag :max_age, 'Maximum Age', class: "block text-sm font-medium text-gray-700"
      =text_field_tag :max_age, params[:max_age], class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block sm:text-sm border-gray-300 rounded-md'

    .col-span-2.flex
      =submit_tag 'Calculate Player Payout', class: "py-2 px-4 self-end border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

-if @player_payout
  | Total Player Payout: #{number_to_currency @player_payout}


.my-5.text-right
  =link_to 'Add Offer', new_offer_path, class: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

.flex.flex-col
  .-my-2.overflow-x-auto.sm:-mx-6.lg:-mx-8
    .py-2.align-middle.inline-block.min-w-full.sm:px-6.lg:px-8
      .shadow.overflow-hidden.border-b.border-gray-200.sm:rounded-lg
        table.min-w-full.divide-y.divide-gray-200
          thead.bg-gray-50
            tr
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Title
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Header
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Description
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Points
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Payout
              th.px-6.py-3.text-left.text-xs.font-medium.text-gray-500.uppercase.tracking-wider[scope="col"]
                | Offer Targets
              th.relative.px-6.py-3[scope="col"]
                span.sr-only
                  | Edit
              th.relative.px-6.py-3[scope="col"]
                span.sr-only
                  | Destroy
          tbody
            -@offers.each do |offer|
              tr.hover:bg-slate-50
                td.px-6.py-4.whitespace-nowrap.text-sm.font-medium.text-gray-900
                  =offer.title
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer.header
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer.description
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =offer.points
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =number_to_currency(offer.payout)
                td.px-6.py-4.whitespace-nowrap.text-sm.text-gray-500
                  =link_to pluralize(offer.offer_targets.count, "Target"), offer_offer_targets_path(offer), class: "text-indigo-600 hover:text-indigo-900"

                td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
                  =link_to 'edit', edit_offer_path(offer), class: "text-indigo-600 hover:text-indigo-900"
                td.px-6.py-4.whitespace-nowrap.text-right.text-sm.font-medium
                  =button_to 'destroy', offer, class: "text-indigo-600 hover:text-indigo-900", method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }

app/views/offers/new.html.slim
=render 'form', title: 'Create New Offer'