config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :devices
  resources :offers do
    resources :offer_targets, path: 'targets', only: [:index]
  end
  
  resources :offer_targets


  root to: 'players#index'
end


# web: bin/rails server -p 3000

app/views/layouts/_nav.html.slim
nav.bg-white.shadow
  .max-w-7xl.mx-auto.px-4.sm:px-6.lg:px-8
    .flex.justify-between.h-16
      .flex
        .flex-shrink-0.flex.items-center
          img.block.lg:hidden.h-8.w-auto[src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow"]
          img.hidden.lg:block.h-8.w-auto[src="https://tailwindui.com/img/logos/workflow-logo-indigo-600-mark-gray-800-text.svg" alt="Workflow"]
        .hidden.sm:ml-6.sm:flex.sm:space-x-8

          -active_classes = "border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"
          -idle_classes = "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"

          =link_to 'Players', players_path, class: nav_hilite(active_classes, idle_classes, players_path)

          =link_to 'Devices', devices_path, class: nav_hilite(active_classes, idle_classes, devices_path)

          =link_to 'Offers', offers_path, class: nav_hilite(active_classes, idle_classes, offers_path)

          =link_to 'Offer Targets', offer_targets_path, class: nav_hilite(active_classes, idle_classes, offer_targets_path)

app/views/layouts/application.html.slim
doctype html
html
  head
    title 
      | InfluenceMobile
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true

  body.flex.flex-col.justify-center
    header.flex-none
      =render 'layouts/nav'

    main#app.mx-auto.mt-20.w-3/4
      =yield

      #search

      #content

    footer.mx-auto.mt-10.mb-48.w-3/4.text-right.text-slate-400
      | Hire Ryan Detert<sup>&trade;</sup>

    = yield(:js)